### ISSUE TITLE
tell users about Gitter room

### ISSUE THREAD

**Issue by SethTisue** [playframework/playframework.com#113]
this came up on scala/scala the other day — a user was asking Play questions, we recommended they use the Play Gitter room and when informed of the existence of https://gitter.im/playframework/playframework, they were surprised because they had looked first on playframework.com and found nothing about it

where should it be added? definitely https://playframework.com/get-involved I would think, under "Find help". perhaps also to the little row of social media icons that show up on every page.

**Comment by SethTisue** [comment]
previously: https://github.com/playframework/playframework/issues/5319

**Comment by wsargent** [comment]
"You can ask on the list if you have any questions, or you can also chat to Play contributors through the gitter.im channel."

**Comment by SethTisue** [comment]
yeah. but that links to playframework/contributors, not playframework/playframework, and it is only introduced in the context of "Patching the core", not on the context of getting help. often the people with questions aren't even Play users yet and just want to ask questions to see if it's suitable for their use case

**Comment by wsargent** [comment]
k, hang on a sec

**Comment by SethTisue** [comment]
LGTM, awesome! fyi @Sciss
