### ISSUE TITLE
I'd like to add link to My user group in home page

### ISSUE THREAD

**Issue by ultimate1352** [playframework/playframework.com#14]
Hi.!

I'm Lawrence from korea republic of.
I'd like to add link to My user group in home page.
The page is "https://www.playframework.com/documentation/$(VERSION)/PlayUserGroups"

How to add it?

Please Help me :)

**Comment by jroper** [comment]
Submit a pull request with your user group added to this file:

https://github.com/playframework/playframework/blob/master/documentation/manual/about/PlayUserGroups.md

**Comment by ultimate1352** [comment]
Thank you jroper.

Closed!
