### ISSUE TITLE
"Browse versions" links in documentation pages should point to the current page in chosen version

### ISSUE THREAD

**Issue by queirozfcom** [playframework/playframework.com#15]
When one is on page "ScalaWS" for version **2.3.x** [link here](https://www.playframework.com/documentation/2.3.x/ScalaWS) and opens the dropdown list on the right-hand side of the page and clicks on version **2.4.x**, one is *not* taken to page "ScalaWS" for version 2.4.x [(this would be the correct link)](https://www.playframework.com/documentation/2.4.x/ScalaWS), but to the main page for version 2.4.x   [(this link)](https://www.playframework.com/documentation/2.4.x/Home).

I know that there will be times when a given page is not available in the target version but we could redirect tthe user to the home page *only in those cases* when there isn't a matching version. I think this is what most users expect.

**Comment by jroper** [comment]
Yeah, I've often thought about this.  Here's a few options:

* Preflight a HEAD request using ajax to check whether it 404s or not.
* Create a version switch endpoint that redirects to the actual page if it exists, or to the home page if not.

**Comment by jroper** [comment]
Implemented and deployed.

**Comment by queirozfcom** [comment]
:+1:
