### ISSUE TITLE
I will translate a documentation of play framework to korean.

### ISSUE THREAD

**Issue by ultimate1352** [playframework/playframework.com#16]
Hello. I'm Lawrence from korea.

I will translate a documentation of play framework to korean.
And I have questions.

1. Where is a english doc?
=> Maybe It is in "https://github.com/playframework/playframework/tree/master/documentation".
Is it right?

2. How to contact the Play team?
=> I read about deploying in a translation page(https://www.playframework.com/documentation/2.3.x/Translations).
But I can't how to contact them.

3. And Do I contant the play team after to translate full doc?
=> I'd like to translate point to point. And I think that It will take about three months.
If it fine some md not translate yet, I hope to deploying my doc in play's web site.

Please, help me. =)
Thanks.

**Comment by jroper** [comment]
Hi @ultimate1352, that sounds great!

The best place to talk about this is on the Play dev mailing list:

https://groups.google.com/forum/#!forum/play-framework-dev

You don't have to have a full translation ready, however, we would like to see a significant start (eg, at least 10 pages).  Also, if at any point before that, you want us to check that you're doing things right, just email us on the mailing list.

I'll close this issue now, so if you have any further questions, ask them on the mailing list.

**Comment by ultimate1352** [comment]
Thanks. @jroper.
It really helpful answer!
