### ISSUE TITLE
Uncomfortable highlighting style

### ISSUE THREAD

**Issue by aaabramov** [playframework/playframework.com#170]
Cloning the ticket https://github.com/playframework/playframework/issues/7776 in appropriate repository:

I am quiet discouraged about highlighting of key words in manuals.
I think that line spacing should be increased a bit because it is really hard to read.

What do you think?

![horrible_style](https://user-images.githubusercontent.com/11317222/29927347-c021ebf6-8e6e-11e7-908f-b3884e1a2d01.png)
<img width="596" alt="screen shot 2017-09-21 at 17 55 12" src="https://user-images.githubusercontent.com/11317222/30702705-4ca4efe6-9ef6-11e7-9246-aee4f0528013.png">

Link: https://www.playframework.com/documentation/2.6.x/GlobalSettings

Browsers: Chrome, Mozilla

**Comment by Abrasha** [comment]
Unfortunately, I do not have enough time to fix this.

**Comment by marcospereira** [comment]
Hey @Abrasha,

About the line height, do you think this is goo enough?

![screen shot 2017-09-21 at 12 39 11 pm](https://user-images.githubusercontent.com/4576/30704735-f97c13b6-9ec9-11e7-971a-24546edf294b.png)

At least the lines aren't overlapping.

WDYT?

**Comment by Abrasha** [comment]
Hi @marcospereira,
Actually, I am not a designer but it much more better!

Is highlighted font somehow scaled comparing to regular text?

**Comment by adis-me** [comment]
Good readability improvement. But still (I am not a designer as well) the border is giving an extra hurdle that we need to filter out. In my opinion we can remove the border as well. Github also `does not use` a border.

## Without a border

<img width="632" alt="screen shot 2017-09-21 at 23 05 27" src="https://user-images.githubusercontent.com/1314455/30718864-b62f7406-9f21-11e7-851b-67d170d7f320.png">

## Change bg color from `#fafafa` into `#f2f2f2`
<img width="614" alt="screen shot 2017-09-21 at 23 05 48" src="https://user-images.githubusercontent.com/1314455/30718868-be1549e8-9f21-11e7-84fe-c850811c714f.png">

**Comment by Abrasha** [comment]
@adis-me much more better, thank you. Does everyone agree with green text color? @marcospereira

**Comment by Abrasha** [comment]
Team, any updates on this?

**Comment by richdougherty** [comment]
Looks good to me!
