### ISSUE TITLE
Broken contribution link

### ISSUE THREAD

**Issue by Abrasha** [playframework/playframework.com#171]
Steps to reproduce:
- Go to https://www.playframework.com/documentation/2.6.x/ScalaJson
- Navigate to the bottom
- Click on `here`

Link address is https://github.com/playframework/playframework/edit/2.6.x/documentation/manual/working/scalaGuide/main/json/ScalaJson.md

I am not sure that it relates only to this page. But at least the same behavior is for https://www.playframework.com/documentation/2.6.x/ScalaJsonCombinators

**Comment by Dulya** [comment]
Possibly this issue is referenced here #86

**Comment by gmethvin** [comment]
yeah this is a duplicate of #86
