### ISSUE TITLE
Fix header size

### ISSUE THREAD

**Issue by aaabramov** [playframework/playframework.com#180]
<img width="855" alt="screen shot 2017-11-02 at 18 05 13" src="https://user-images.githubusercontent.com/11317222/32336627-7733a14e-bff8-11e7-992d-bbaed9af783c.png">

Link with anchor: https://www.playframework.com/documentation/2.6.x/Migration26#play.api.libs.concurrent.Execution-is-deprecated

Maybe it should be replaced with `###` in markup instead of `##`?

**Comment by wsargent** [comment]
This is something that is in the main project itself, under documentation:

https://github.com/playframework/playframework/blob/master/documentation/manual/releases/release26/migration26/Migration26.md#playapilibsconcurrentexecution-is-deprecated

I think it's more an issue of the preformatted text together with one single long word causing overflow.

**Comment by marcospereira** [comment]
[`overflow-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) should fix this.

**Comment by marcospereira** [comment]
Using `overflow-wrap` results in the following:

<img width="658" alt="screen shot 2018-05-02 at 1 46 34 pm" src="https://user-images.githubusercontent.com/4576/39537227-48ef5ec2-4e0f-11e8-8d84-09bcf4326132.png">

No amazing but better. @aaabramov what do you think?

**Comment by sizer** [comment]
@marcospereira @wsargent 
I created PR as https://github.com/playframework/playframework.com/pull/260.
How about this?

**Comment by marcospereira** [comment]
Fixed by #260.
