### ISSUE TITLE
Image path is error in main.min.css created by sbt-stylus plugin on windows platform

### ISSUE THREAD

**Issue by akuoo** [playframework/playframework.com#217]
I clone the source and start the server on windows 7.
The is something wrong with the image path in main.min.css,which is created by sbt-stylus.
![default](https://user-images.githubusercontent.com/12652309/42981506-fbc70f12-8c0e-11e8-82e4-cc55fe3b4568.png)

I diff the code with the offical website and found the difference:
On the offical websit, the logo image path is 
"https://www.playframework.com/assets/images/logos/play_full_color.svg"
but,On my local server, the logo image path is 
"http://localhost:9000/assets/css/\assets\images\logos\play_full_color.svg"
Bellow is the screenshot.
I'm not good at stylus, is there any help?

![default](https://user-images.githubusercontent.com/12652309/42981357-4c154778-8c0e-11e8-8647-3c3f86315609.png)
![default](https://user-images.githubusercontent.com/12652309/42981383-6c2586cc-8c0e-11e8-9e94-c79d10f938f6.png)

**Comment by marcospereira** [comment]
Better if you open an issue on sbt-stylus since we don't develop/deploy the website on Windows. Also, a fix won't be made here, but instead on sbt-stylus if there is a problem.
