### ISSUE TITLE
Fix formatting on RabbitMQ module's page

### ISSUE THREAD

**Issue by aaabramov** [playframework/playframework.com#229]
Link: [Rabbit module](https://www.playframework.com/modules/rabbitmq-0.0.9/home)

**Comment by marcospereira** [comment]
Thanks, @aaabramov.

I think this belongs in here: 

https://github.com/feliperazeek/play-rabbitmq/blob/master/documentation/manual/home.textile

So I'm closing this.

**Comment by aaabramov** [comment]
@marcospereira seems that repo is dead.
Should playframework.com host obsolete guides?
