### ISSUE TITLE
Wrong link to Hello World Example

### ISSUE THREAD

**Issue by rstento** [playframework/playframework.com#245]
In the Getting Started section of the documentation, the link pointed to the old Play starter examples.

**Comment by wsargent** [comment]
Also in the pinned section of the Play github repo: https://github.com/playframework/

**Comment by wsargent** [comment]
https://www.playframework.com/getting-started has 

Play 2.7.x Hello World Projects
--

but no projects :-/

**Comment by wsargent** [comment]
Looks like the underlying cause is that https://example.lightbend.com/v1/api/templates (referenced from the PlayExamples service) only contains the https://github.com/playframework/play-java-hello-world-tutorial/tree/2.6.x versions

**Comment by rstento** [comment]
It is fixed now, closing
