### ISSUE TITLE
Language management issue on playframework.com

### ISSUE THREAD

**Issue by schidaine** [playframework/playframework.com#252]
Using a french browser to get latest documentation. I use the “Documentation 2.7.0” button which opens French doc in 2.4.x and no information about 2.7.x.

Furthermore :
I switch to english (I know the issue now). A small banner tells me I’m not consulting the latest doc. " You are viewing the documentation for the 2.4.x release series. The latest stable release series is 2.7.x". But the link under “2.7.x” is https://www.playframework.com/documentation/en-US/2.7.x/Home which goes nowhere. The correct one is https://www.playframework.com/documentation/switch/2.7.x/Home

**Comment by sizer** [comment]
any progress??

**Comment by dwijnand** [comment]
> Furthermore :
> I switch to english (I know the issue now). A small banner tells me I’m not consulting the latest doc. " You are viewing the documentation for the 2.4.x release series. The latest stable release series is 2.7.x". But the link under “2.7.x” is [playframework.com/documentation/en-US/2.7.x/Home](https://www.playframework.com/documentation/en-US/2.7.x/Home) which goes nowhere. The correct one is [playframework.com/documentation/switch/2.7.x/Home](https://www.playframework.com/documentation/switch/2.7.x/Home)

That was also reported in https://github.com/playframework/playframework/issues/9076, which I fixed in https://github.com/playframework/playframework.com/pull/261.
