### ISSUE TITLE
[doc] Translations should have fallback navigation to English version

### ISSUE THREAD

**Issue by exoego** [playframework/playframework.com#285]
### Expected Behavior

Every translated versions of document should have 

* Older version notice
* Navigation to latest stable version
* Fallback to English version if there is no translation of the version

so that readers and Google crawlers can find there is newer version document, at least in English.

### Actual Behavior

There is already such features: 
![image](https://user-images.githubusercontent.com/127635/45603898-ea4c4700-ba69-11e8-8aa1-9d237e9801c0.png)

However,

* Vely little translated version has such older version notice and navigation to latest.
* Turkish version has them, but it is hard to know there is already 2.6.x in English version.
* "Documentation" link redirect users to translated version (based on browser language/cookie, I guess) 
    * ![image](https://user-images.githubusercontent.com/127635/45604059-b8d47b00-ba6b-11e8-81c1-0c1bfd27b031.png)

Therefore, some users can not reach to latest document (2.16.x, as of today).

#### Bulgarian
* Latest:  2.4.x 
* Older version notice: No
* Navigation to latest: No
* Fallback to English version (2.16.x): No
![image](https://user-images.githubusercontent.com/127635/45603595-53cb5600-ba68-11e8-929e-b289b94e226f.png)

#### French
* Latest:  2.4.x 
* Older version notice: No
* Navigation to latest: No
* Fallback to English version (2.16.x): No
![image](https://user-images.githubusercontent.com/127635/45603589-4910c100-ba68-11e8-9258-229f5347db8f.png)

#### Japanese
* Latest:  2.4.x 
* Older version notice: No
* Navigation to latest: No
* Fallback to English version (2.16.x): No
![image](https://user-images.githubusercontent.com/127635/45603583-37c7b480-ba68-11e8-8419-35ab38571d72.png)

#### Turkish
* Latest:  2.5.3 
* Older version notice: Yes
* Navigation to latest: Yes
* Fallback to English version (2.16.x): No
![image](https://user-images.githubusercontent.com/127635/45603579-29799880-ba68-11e8-866f-023a0545422e.png)

**Comment by marcospereira** [comment]
I believe this was fixed by #265.

So I'm closing it. @exoego, let me know if you think it is still not working as you expect.
