### ISSUE TITLE
Play website documentation links

### ISSUE THREAD

**Issue by guizmaii** [playframework/playframework.com#286]
Hi,

It seems that there's a problem with the Playframework documentation website.

1. All the links to the documentation in https://www.playframework.com redirect to https://www.playframework.com/documentation/fr/2.4.x/Home

2. Latest version of the documentation is missing. https://www.playframework.com/documentation/fr/2.6.x/Home redirect to a "Page not found" page.

<img width="1792" alt="capture d ecran 2018-04-02 19 33 01" src="https://user-images.githubusercontent.com/1193670/38207009-b0283f66-36ac-11e8-84f2-1ff2def27d9f.png">

**Comment by marcospereira** [comment]
@guizmaii I'm closing this since it was fixed by #265. Let me know if there is still a problem. :-)
