### ISSUE TITLE
Page not found [ Home ]

### ISSUE THREAD

**Issue by sizer** [playframework/playframework.com#292]
Hi, guys.
I can not open link
https://www.playframework.com/documentation/2.7.x/Home
this url is placed on https://playframework.com as `Documentation 2.7.1` .

Response code is 404.
Log is below.

What's wrong ?? :thinking: 

```bash
sizer@geb:~
$ curl -D - -s  -o /dev/null https://www.playframework.com/documentation/2.7.x/Home
HTTP/2 404 
date: Fri, 26 Apr 2019 12:14:59 GMT
content-type: text/html; charset=UTF-8
set-cookie: __cfduid=df901702e91679f002637a0f21b5b0dc21556280898; expires=Sat, 25-Apr-20 12:14:58 GMT; path=/; domain=.playframework.com; HttpOnly
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
x-frame-options: sameorigin
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-permitted-cross-domain-policies: master-only
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 4cd87abe2915aee1-KIX
```

**Comment by mkurz** [comment]
This is a known issue and actively being worked on.
As a workaround you can use:
https://www.playframework.com/documentation/2.7.1/Home

**Comment by ignasi35** [comment]
Hi @sizer,

thanks for raising the flag on this one. The issue is solved in https://github.com/playframework/playframework/pull/9226

Cheers
