### ISSUE TITLE
Download not working anymore!

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework.com#31]
https://groups.google.com/forum/?fromgroups=#!topic/play-framework/YGvD4Lhdr_w

It's because the zip files are not served via `https`.

The url's don't contain `https` when fetched from typesafe:
https://www.typesafe.com/activator/latest

Either we have to convert the urls to `https` [here](https://github.com/playframework/playframework.com/blob/541d0cfe14c229457be3c3ef1865494bad87d606/app/actors/ActivatorReleaseActor.scala#L31-L57) somewhere or the received json has to be fixed.

**Comment by richdougherty** [comment]
#32 should have fixed this now. Do you want to check?

**Comment by mkurz** [comment]
Thanks! It's working now! :+1:

**Comment by richdougherty** [comment]
Great!
