### ISSUE TITLE
10-minute refresh of docs not working

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework.com#382]
playframework.com should display content recently pushed to `play-generated-docs` with, at-most, a 10-minute delay. As stated in the [release process](https://github.com/playframework/play-meta/blob/master/releasing/play.md#step-3---release-omnidoc):

> Verification: ... The website should pick this tagged version of the generated docs up to 10 minutes later. You can check that then using the following URL pattern: https://www.playframework.com/documentation/<tag>/Home. For example playframework.com/documentation/2.7.2/Home.

This is not working as expected. During the release of both `2.7.5` and `2.8.2`, even if the tags in https://github.com/playframework/play-generated-docs/releases existed, the site produces the Play's `Page not found [ Home ]` page.

**Comment by mkurz** [comment]
For me this was working for the 2.8.12 release, the docs appeared after a couple of minutes at https://www.playframework.com/documentation/2.8.12/Home I can also confirm that docs that changed only in the 2.8.12 tag from the generated-docs appeared. So the sync mechanism did work again (I did only push the generated docs yet, not the play website)

**Comment by mkurz** [comment]
Worked again for the 2.8.13 release. Let's close for now.
