### ISSUE TITLE
Japanese characters are corrupted

### ISSUE THREAD

**Issue by tkawachi** [playframework/playframework.com#41]
All Japanese characters are displayed as question marks.

A screenshot of https://www.playframework.com/documentation/ja/2.3.x/Home is below:
![screen shot 2015-10-26 at 20 51 39](https://cloud.githubusercontent.com/assets/22657/10728233/67930af6-7c23-11e5-9160-52345c35db16.png)

Contribution note at the bottom is OK.
![screen shot 2015-10-26 at 20 51 46](https://cloud.githubusercontent.com/assets/22657/10728234/6921954a-7c23-11e5-95fd-f993aca83bb9.png)

Turkish translation also contains similar question marks. But I'm not sure whether it's broken or issue of my font environment.

**Comment by tkawachi** [comment]
Apparently, English pages also have corrupted chars.

https://www.playframework.com/documentation/2.4.x/ScalaRouting#Reverse-routing
![screen shot 2015-10-26 at 22 45 21](https://cloud.githubusercontent.com/assets/22657/10730498/ad327302-7c33-11e5-995c-ec457c5eb164.png)

**Comment by xuwei-k** [comment]
fixed ? https://github.com/playframework/playframework.com/commit/0e8ed5571e2c71

**Comment by tkawachi** [comment]
It seems to be fixed. Thanks @jroper !
