### ISSUE TITLE
Play 1.x modules download broken 

### ISSUE THREAD

**Issue by criluc** [playframework/playframework.com#442]
The modules under https://www.playframework.com/modules/
are unavailable and access to modules give a 404 http error. 

See for example 
https://www.playframework.com/modules/table-1.2.2.zip

This modules are fundamental in order to build play 1.x apps.

**Comment by ignasi35** [comment]
Play1 modules should be back online on playframework.com. The solution is a hack and we'll create a better implementation to no longer face this kind of downtime.

More info at https://github.com/playframework/playframework.com/pull/443 and https://github.com/playframework/play-meta/pull/184

**Comment by marcospereira** [comment]
The modules are back online. Closing.

**Comment by tomparle** [comment]
Thanks for fixing this so rapidly !
