### ISSUE TITLE
%PLAY_VERSION% should be rendered as latest version for *.*.x

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework.com#45]
For example in https://www.playframework.com/documentation/2.4.x/NewApplication we have:
```scala
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.x")
```
which doesn't really make sense. It should just render as the latest version in 2.4.x series.

**Comment by gmethvin** [comment]
Only issue I see here is that (technically) the .x docs currently represent the docs on that branch but don't correspond to an actual release yet. So it's possible that something there won't work exactly on whatever the latest release is.

**Comment by wsargent** [comment]
@gmethvin did you mean to file this on playframework/playframework?  This looks like a doc bug...

**Comment by gmethvin** [comment]
I was under the impression that those variables are set in the documentation rendering code on playframework.com.

**Comment by wsargent** [comment]
I believe that's coming out of play-doc: 

https://github.com/playframework/play-doc/blob/master/src/main/scala/play/doc/PlayDoc.scala#L50

**Comment by gmethvin** [comment]
@wsargent Okay, yeah, this should probably be filed against play-doc.

**Comment by gmethvin** [comment]
See playframework/play-doc#20
