### ISSUE TITLE
Host website and docs outside Lightbend

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework.com#451]
Before thinking about a different approach how we host the docs and the website, we should just quickly set up a own virtual machine (AWS, DigitalOcean, whatever) where we can move the Play website to.

Important:
- https://github.com/playframework/play-meta/issues/104

**Comment by igmar** [comment]
@mkurz Can we discuss which route to take ? I'm willing to pick this up further.

**Comment by mkurz** [comment]
@igmar Thanks for your offer to help (and sorry for the very late reply). Since Play moved to Open Collective and as a part of that also has a (virtual) credit card available, plus given the fact that the Play website currently is hosted on a AWS EC2 instance, I think the best solution is if the Play team just sets up a AWS account and migrates the existing VM over to Play's AWS account then.
Also, what we are doing right now, we want to make the infrastructure as independent as possible from any individual person, so we are setting up official Play accounts for every service we use and share secrets between the Play steering committee members, so in case someone leaves the steering committee other members can just continue without any hassles.
Thanks for you offer anyway!

**Comment by igmar** [comment]
@mkurz Full understandable. If you need help moving things over to the target state, let me know. I have extensive linux / AWS knowledge.

**Comment by ennru** [comment]
Lightbend is happy to continue sponsorship of Play by managing the playframework.com domain and the current AWS machine for the documentation site.

**Comment by mkurz** [comment]
I am closing this for now. We keep the website on Lightbend's VM for now, since there is a lot of other work to do and this definitely is not high priority. We can move out from Lightbend anytime needed (e.g. in case we change how to publish/host the documentation we might come back to this issue).

**Comment by mkurz** [comment]
Needs to be done in the next months.

**Comment by mkurz** [comment]
Goes hand in hand with #104

**Comment by mkurz** [comment]
We run our own vm now. But this should also be just temporary until we finally move everything to github pages....
