### ISSUE TITLE
Remove books (?)

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework.com#472]
It's sad but basically all the books listed on the right at https://www.playframework.com/documentation/latest are totally outdated.
* Play for Scala is from 2013 and is about Play 2.1
* Play for Java is from 2014 and is about Play 2.2
* Learning Play! Framework 2 is from 2013 and probably probably is about Play 2.1 or 2.0
* Play Framework Essentials is from 2014 and maybe is about Play 2.3 already (but maybe 2.2...)
* Reactive web applications is from 2016 and uses Play 2.4

To illustrate: Play 2.1 and 2.2 were still using the `play` command. Play 2.3 switched to activator...
We could keep "Reactive web applications", also because it's not just about Play but more general... (but it also still uses activator)

I did a quick search on amazon, the only books I could find which kind of looks newer are
* "[Introducing Play Framework: Java Web Application Development](https://www.amazon.de/Introducing-Play-Framework-Application-Development/dp/1484256441/)" which is about Play 2.7.
* "[Scala Programming Projects: Build real world projects using popular Scala frameworks like Play, Akka, and Spark](https://www.amazon.de/Scala-Programming-Projects-projects-frameworks/dp/1788397649/ref=sr_1_11)" which already mentiones sbt, however it was first published in Sept. 2018, even before Play 2.7 was released...

BTW: Als the links the books refer to go to a Lightbend page that doesn't even list these books anymore...

**Comment by ihostage** [comment]
Our choice between "no books" and "outdated books", right?

**Comment by Max-AR** [comment]
Hi, I added the PR above that removes the books from the site but I didn't realize this issue was here. My thought process was if there is incorrect or outdated information in the the docs it should be removed so we don't accidentally confuse people. 

Happy to adjust anything in that PR should we make and decisions here!

**Comment by mkurz** [comment]
Books got removed in #475
We can add books again if they get updated or new releases.
