### ISSUE TITLE
Search does not work 

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework.com#562]
:cry:

**Comment by mkurz** [comment]
It's working in

* https://www.playframework.com/documentation/2.8.x/Home

but not the **newly added** 2.9.x and 3.0.x docs:

* https://www.playframework.com/documentation/2.9.x/Home
* https://www.playframework.com/documentation/3.0.x/Home

Pretty sure the Algolia index needs to be configured to also crawl those two "subfolders".
I am in contact with Lightbend already since they still manage the algolia account. They will take a look.
Also asking them to transfer the algolia index to us... We will see.

**Comment by PromanSEW** [comment]
Any news?

**Comment by mkurz** [comment]
Yeah sorry for the long delay, I am working on it, just algolia support takes some time (also I was not pushing hard enough...).
I wrote them once more, I am also in contact with Lightbend, to finally hand over the Algolia account but things take a bit longer then desired (they couldn't find the credentials...). But we are getting there slowly. I hope to resolve this the next days, really :crossed_fingers:

**Comment by mkurz** [comment]
Bust to let you know I am working on this again, I need to set up a new algolia account because we can not retrieve the old one and support can not help us (or not willing to...)

**Comment by mkurz** [comment]
So, I finally figured all the things out, spend basically the last two days reading Algolia docs, contacting even more people, trying various things with different docsearch version and  crawler versions (because Play currently uses a very old legacy Algolia implementation which actually needed to be upgraded etc)... it was a bit complicated, but I can replicate the search now again locally already. I am an Algolia export now...
I am too tired now, but will post more about that tomorrw (and also will finally make the search work again, future proof)

**Comment by mkurz** [comment]
Done, search is working now again for all versions. Also, no crawl errors occured anymore.
Bonus: New releases will be crawled auomatically, because https://www.playframework.com/releases is now the entry point for crawling, which has hidden links to all versions. Algolia crawler visits once per week on Tuesday. Crawling and indexing all pages of all versions now takes ~ 2 hours and 20 minutes.

Finally we now have control with our own Algolia account.
RIP old Algolia account that no one is able to restore anymore :coffin: (including Algolia staff...)
