### ISSUE TITLE
Change the Google Search to algolia

### ISSUE THREAD

**Issue by schmitch** [playframework/playframework.com#62]
Actually the current search of the Playframework Docs isn't really good, it would be great to have the same search experience than akka.io (they use https://www.algolia.com)

**Comment by ktoso** [comment]
I'll get you guys in touch with the right people to get this set up :+1:

**Comment by ktoso** [comment]
Fun fact, we use it because I found docs.scala-lang.org/style/ was using it.
So far it's really awesome!
