### ISSUE TITLE
Show latest version of docs in Google results

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework.com#8]
At the moment, when someone searches Google for Play documentation, they will usually get documentation for some random version of Play. E.g. searching for *[play framework ws](https://www.google.com/search?q=play+framework+ws)* gives results in the following order: 2.2.x Scala, 2.1.0 Scala, 2.4.x Scala, 2.1-RC1 Scala, 2.1.1 Java, 1.1, …

But the latest stable version of Play is 2.3.x, so we what we really want is 2.3.x Scala and 2.3.x Java to be the top results.

We should be able to achieve this by generating a sitemap for playframework.com and using the [priority tag](http://www.sitemaps.org/protocol.html#prioritydef) to put the latest stable versions at the top of search results.

**Comment by wsargent** [comment]
Sitemaps URLs: https://support.google.com/webmasters/answer/183668?hl=en and http://www.sitemaps.org/protocol.html

**Comment by wsargent** [comment]
Okay, canonical headers are deployed.   We'll see how well Google SEO works...

**Comment by wsargent** [comment]
This is now fixed.
